sudo: required
services:
  - docker
before_install:
  - docker build -t mitpat/docker-redis -f Dockerfile.dev .
script:
  - docker run mitpat/docker-redis npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockerapp"
  env: "Dockerapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-891730512940"
  bucket_path: "dockerapp"
  on:
    branch: master  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"   